(defun tos ()
  (format t "Tossing a coin...~%")
  (let ((head 0) (tail 0))
    (dotimes (i 3)
      (cond ((= (random 2) 0)
	     (format t "Round ~a: Heads~%" (+ i 1))
	     (setf head (+ head 1)))
	    (t
	     (format t "Round ~a: Tails~%" (+ i 1))
	     (setf tail (+ tail 1)))))
    (format t "Heads: ~a, Tails: ~a~%" head tail)
    (if (> head tail) (format t "You won!~%") (format t "You lose.~%"))))
